joint_state_controller:
  type: joint_state_controller/JointStateController
your_robot_arm_controller:
  type: hardware_interface/PositionJointInterface
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6