controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    xarm6_traj_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    xarm6_velo_traj_controller:
      type: velocity_controllers/JointGroupVelocityController

xarm6_traj_controller:
  ros__parameters:
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    constraints:
      goal_time: 0.5
      stopped_velocity_tolerance: 0.0
      joint1: {trajectory: 1.0, goal: 0.01}
      joint2: {trajectory: 1.0, goal: 0.01}
      joint3: {trajectory: 1.0, goal: 0.01}
      joint4: {trajectory: 1.0, goal: 0.01}
      joint5: {trajectory: 1.0, goal: 0.01}
      joint6: {trajectory: 1.0, goal: 0.01}
    interface_name: position
    state_publish_rate: 25.0
    action_monitor_rate: 10.0


xarm6_velo_traj_controller:
  ros__parameters:
    command_interfaces:
      - velocity
    state_interfaces:
      - velocity
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    gains:
      joint1: {p: 10, i: 0.0, d: 0.0, i_clamp: 1}
      joint2: {p: 10, i: 0.0, d: 0.0, i_clamp: 1}
      joint3: {p: 10, i: 0.0, d: 0.0, i_clamp: 1}
      joint4: {p: 10, i: 0.0, d: 0.0, i_clamp: 1}
      joint5: {p: 10, i: 0.0, d: 0.0, i_clamp: 1}
      joint6: {p: 10, i: 0.0, d: 0.0, i_clamp: 1}
    velocity_ff:
      joint1: 0.25
      joint2: 0.25
      joint3: 0.25
      joint4: 0.25
      joint5: 0.25
      joint6: 0.25
    constraints:
      goal_time: 0.5
      stopped_velocity_tolerance: 0.01
      joint1: {trajectory: 1, goal: 0.01}
      joint2: {trajectory: 1, goal: 0.01}
      joint3: {trajectory: 1, goal: 0.01}
      joint4: {trajectory: 1, goal: 0.01}
      joint5: {trajectory: 1, goal: 0.01}
      joint6: {trajectory: 1, goal: 0.01}
    stop_trajectory_duration: 0.2
    state_publish_rate:  25
    action_monitor_rate: 10

# controller_manager:
#   ros__parameters:
#     update_rate: 100  # Hz, adjust as necessary based on your real-time requirements

#     joint_state_broadcaster:
#       type: joint_state_broadcaster/JointStateBroadcaster

#     velocity_controller:
#       type: velocity_controllers/JointGroupVelocityController
#       joints:
#         - joint1
#         - joint2
#         - joint3
#         - joint4
#         - joint5
#         - joint6

# # Namespace configurations for the velocity controller
# velocity_controller:
#   ros__parameters:
#     # Define command interfaces for each joint, here assumed to be 'velocity'
#     command_interfaces:
#       - velocity
#     # Define state interfaces for each joint, often 'position' and 'velocity'
#     state_interfaces:
#       - position
#       - velocity
#     # Topic on which to publish velocity commands
#     topic_name: /velocity_controller/commands
