controller_manager:
  ros__parameters:
    update_rate: 100  # Hz, adjust as necessary based on your real-time requirements

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
      joints:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6

# Namespace configurations for the velocity controller
velocity_controller:
  ros__parameters:
    # Define command interfaces for each joint, here assumed to be 'velocity'
    command_interfaces:
      - velocity
    # Define state interfaces for each joint, often 'position' and 'velocity'
    state_interfaces:
      - position
      - velocity
    # Topic on which to publish velocity commands
    topic_name: /velocity_controller/commands
